### ISSUE TITLE
如何指定消息推送到某个客户端id

### ISSUE THREAD

**Issue by 617450941** [liutian/push#3]
我看了下push接口 没有指定客户端id的参数

**Comment by liutian** [comment]
单独推送到某个客户端的场景很少见，一般都是推送到某个用户或者某个房间，所以没有开发此功能

**Comment by 617450941** [comment]
我说错了 是指推送给某个用户 我看文档都是具体推送到某个房间号

**Comment by liutian** [comment]
每一个客户端上线时至少会进入一个默认房间，房间名: user_ + userid，如果需要给单个用户推送消息，可以设定推送房间为用户的默认房间即可，已经更新到README.md功能特性
