### ISSUE TITLE
根据项目提供的Dockerfile生成的镜像 无法启动呀

### ISSUE THREAD

**Issue by 617450941** [liutian/push#5]
根据项目提供的Dockerfile生成的镜像 无法启动呀

**Comment by liutian** [comment]
能描述一下你的docker环境吗？是安装在云服务器上，还是vm虚拟机，还是win，可以通过命令：sudo docker exec -it  light-push-demo /bin/bash  进入容器内，然后 pm2 logs 查看启动情况

**Comment by 617450941** [comment]
vm虚拟机

**Comment by liutian** [comment]
pm2 logs 输出什么内容？
