### ISSUE TITLE
请问怎么在windows上怎么部署测试？

### ISSUE THREAD

**Issue by huxiaoqiao** [liutian/push#6]
我是一个Android开发者，现在公司项目要在内网中实现推送，想用该项目做一下测试，但是对后端了解有限，请问在windows上怎么部署测试？

**Comment by liutian** [comment]
下载桌面版docker  https://www.docker.com/get-started     
链接地址  https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe     

在软件中 执行命令   docker run -id -p 443:443 -p 80:80 --name light-push-demo liuss/light-push:1.2.0 /mnt/data/start.sh

然后打开浏览器 输入地址 https://127.0.0.1/push-admin 
登录名 admin 密码 123456

如果无法打开页面建议关闭win防火墙再试或者修改端口重新启动，比如

 docker run -id  -p 10080:80 --name light-push-demo liuss/light-push:1.2.0 /mnt/data/start.sh
然后打开页面地址  http://127.0.0.1:10080/push-admin

**Comment by huxiaoqiao** [comment]
感谢！
